### PR TITLE
fix(quota): correct minimax coding plan URL and usage calculation

### LINKED ISSUE #759: [Bug] MiniMax Coding Plan Usage returns 403
### What's wrong? Maybe some steps to reproduce.

Image

### Where does it happen?

Desktop (macOS)

### Version (if known)

1.9.1

### Screenshots / recordings (optional)

_No response_

### Logs (optional)

```shell

```

### PR DESCRIPTION
**Pull request by baruchvitorino**
Fixes #759

## Summary
- Fix minimax coding plan usage returning 403 error by correcting endpoint URL from `www.minimax.io` to `api.minimax.io`
- Fix inverted usage percentage calculation that was showing remaining credits instead of used credits
- Split providers into independent files (no shared.js)

## Changes
- `minimax-coding-plan.js`: Complete independent provider for minimax.io
  - Fix: Change endpoint from `www.minimax.io` to `api.minimax.io`
  - Fix: Use `intervalUsage` directly instead of `intervalTotal - intervalUsage`
- `minimax-cn-coding-plan.js`: Complete independent provider for minimaxi.com
  - Same calculation fixes applied
- Remove `minimax-shared.js` - providers are now completely separate as requested

## Technical Details
The original `minimax-shared.js` had two bugs:
1. Wrong endpoint URL causing 403 errors
2. Inverted usage calculation: `intervalTotal - intervalUsage` calculated remaining credits, not used credits

Both providers now have their own complete implementation without shared dependencies.

## Testing
- API returns 403 on `www.minimax.io` but works on `api.minimax.io`
- Usage calculation now correctly shows percentage of credits used

### CODE REVIEW

File: packages/web/server/lib/quota/providers/minimax-cn-coding-plan.js [hunk 1]
```diff
@@ -1,15 +1,141 @@
...
+      return buildResult({
+        providerId,
+        providerName,
+        ok: false,
+        configured: true,
+        error: baseResp.status_msg || `API error: ${baseResp.status_code}`,
+      });
+    }
+
+    const firstModel = payload?.model_remains?.[0];
```
Comment (nzlov) [inline packages/web/server/lib/quota/providers/minimax-cn-coding-plan.js:71]: search `MiniMax-M*`

File: packages/web/server/lib/quota/providers/minimax-coding-plan.js [hunk 2]
```diff
@@ -1,15 +1,139 @@
...
+      return buildResult({
+        providerId,
+        providerName,
+        ok: false,
+        configured: true,
+        error: baseResp.status_msg || `API error: ${baseResp.status_code}`,
+      });
+    }
+
+    const firstModel = payload?.model_remains?.[0];
```
Comment (nzlov) [inline packages/web/server/lib/quota/providers/minimax-coding-plan.js:70]: search `MiniMax-M*`
